# Generated by Django 4.2.13 on 2024-11-15 09:11

import bands.models
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    """Pocatecni inicializace dat at nemusime vypisovat rucne..."""
    # Načte data z fixture souborů
    call_command('loaddata', 'genres.json', app_label='bands')
    call_command('loaddata', 'bands.json', app_label='bands')
    call_command('loaddata', 'albums.json', app_label='bands')
    call_command('loaddata', 'songs.json', app_label='bands')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('band__name', 'year'),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.album')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('still_active', models.BooleanField(blank=True, default=False)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.genre')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, bands.models.GetDataEngine),
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.band'),
        ),
        # Pocatecni migrace dat
        migrations.RunPython(load_fixtures),
    ]
